version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8087:8087"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
