version: '3.8'

services:
  backend:
    build:
      context: ./edo_euler
      dockerfile: Dockerfile
    container_name: modelamiento-backend
    ports:
      - "5001:5001"
    restart: always

  frontend:
    build:
      context: ./Restaurante
      dockerfile: Dockerfile
    container_name: modelamiento-frontend
    ports:
      - "8087:80"
    depends_on:
      - backend
    restart: always